tmp

diff --git a/.woodpecker.yaml b/.woodpecker.yaml
--- a/.woodpecker.yaml
+++ b/.woodpecker.yaml
@@ -46,15 +46,20 @@ steps:
         chmod +x /tmp/push-hook.sh
         echo "post-build-hook = /tmp/push-hook.sh" >> /etc/nix/nix.conf
 
+        EXIT_CODE=0
         # ALLOWED='vllm-6.1|whisper-6.1'
         # ALLOWED='^vllm$'
         # ALLOWED='vllm-6.1'
         # ALLOWED='vllm-12.0'
-        ALLOWED='whisper-6.1|container-base'
+        # ALLOWED='whisper-6.1|container-base'
+        ALLOWED='^(whisper-|vllm-|container-base)'
         for PACKAGE in $(nix flake show --json | jq -r '.packages["x86_64-linux"] | keys | .[]' | grep -E "$ALLOWED"); do
 
           log "Building $PACKAGE"
-          nix build .#"\"$PACKAGE\"" -L
+          if ! nix build .#"\"$PACKAGE\"" -L; then
+            log "Building $PACKAGE failed"
+            EXIT_CODE=1
+          fi
 
           if [[ "$PACKAGE" == container-* ]]; then
             log "Pushing $PACKAGE to ghcr.io"
@@ -65,3 +70,5 @@ steps:
           fi
 
         done
+
+        exit "$EXIT_CODE"
